apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: kadhichawal/python-app:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: python-app-config
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: python-app-secret
              key: API_KEY

